#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

DIRNAME=$(dirname "$0")
USER=$(whoami)

TARGET="Launchterm"
DOMAIN="com.msanders.Launchterm"
SUPPORT_DIR="$HOME/Library/Application Support/$TARGET"
AGENT_DIR="$HOME/Library/LaunchAgents"
PLIST="$AGENT_DIR/$DOMAIN.plist"

mkdir -p "$SUPPORT_DIR"
mkdir -p "$AGENT_DIR"

swiftc "$DIRNAME/Launchterm.swift" -o "$SUPPORT_DIR/$TARGET" -O \
                                   -whole-module-optimization

sed -e "s/{USER}/$USER/" "$DIRNAME/$DOMAIN.plist.template" > "$PLIST"

if launchctl list | grep "$DOMAIN" &>/dev/null; then
    launchctl unload "$PLIST"
fi

launchctl load "$PLIST"
echo "Installed $TARGET."
