#!/usr/bin/env bash
# From https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -o errexit
PATH="/usr/local/bin:$PATH"
dir=$(git rev-parse --git-dir)
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files --recurse-submodules | \
    grep -v "\\.\\(playground\\|xcworkspace\\|xcodeproj\\)" | \
    ctags -e --tag-relative -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/TAGS"
echo "ctags index created at $dir/TAGS"
