#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

DIRNAME=$(dirname "$0")
TARGET="Westminster"
DOMAIN="com.msanders.westminster"
AGENT_DIR="$HOME/Library/LaunchAgents"
PLIST="$AGENT_DIR/$DOMAIN.plist"
SUPPORT_DIR="$HOME/Library/Application Support/$TARGET"

rm -rf "$SUPPORT_DIR"
mkdir -p "$SUPPORT_DIR"
mkdir -p "$AGENT_DIR"

cp "$DIRNAME/westminster" "$SUPPORT_DIR"
cp "$HOME"/Dropbox/Westminster/*.m4a "$SUPPORT_DIR"
sed -e "s/{USER}/$(whoami)/" "$DIRNAME/$DOMAIN.plist.template" > "$PLIST"

if launchctl list | grep "$DOMAIN" &>/dev/null; then
    launchctl unload "$PLIST"
fi

launchctl load "$PLIST"
echo "Installed $TARGET."
