#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

AUDIO_DIR="$HOME/Dropbox/Westminster"
PATH="/usr/local/bin:$PATH"

function notify() {
    local msg title
    title="$(echo -e "\xf0\x9f\x94\x94")"
    msg="It is $1."
    echo "$title: $msg"
    terminal-notifier -title "$title" \
                      -message "$msg" \
                      -sender "com.flexibits.fantastical2.mac" \
                      -timeout 30 \
                      -group "com.msanders.westminster" >/dev/null
}

function dim() {
    sleep "$1"
    sleep "$2"
}

function chime() {
    local minute suffix
    minute="$(date +"%M")"
    case "$minute" in
        00) suffix="full" ;;
        15) suffix="first" ;;
        30) suffix="half" ;;
        45) suffix="third" ;;
        *) suffix="" ;;
    esac

    if [[ ! -z "$suffix" ]]; then
        notify "$(date +"%H"):$(printf "%0.2d" "$minute")" &
        dim 2 20 &
        afplay -q 1 "$AUDIO_DIR/chime-$suffix.m4a"

        # The full hour chime is followed by one strike for the number of the
        # hour by Big Ben (one strike for one o'clock, two strikes for two
        # o'clock, etc.).
        #
        # https://en.wikipedia.org/wiki/Westminster_Quarters
        if [[ "$minute" -eq 0 ]]; then
            local hour
            hour="$(date +"%H")"
            if [[ "$hour" -gt 12 ]]; then hour=$(echo "$hour" - 12 | bc); fi

            for _ in $(seq 1 "$hour"); do
                afplay -q 1 "$AUDIO_DIR/chime-ben.m4a"
            done
        fi
    fi
}

chime
